tap 'homebrew/cask'
tap 'homebrew/core'
tap "homebrew/cask-fonts"
tap "ktr0731/evans"
brew "ripgrep"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "npm"
brew "nvm"
brew "kubectl"
brew "ghq"
brew "peco"

brew "bat"
brew "eza"
# コマンド検索
brew "atuin"

brew "jq"
brew "ynqa/tap/jnv"
brew "yq"
brew "fzf"

brew "go-to-k/tap/cls3"
brew "fujiwara/tap/tracer"
# 移動コマンド
brew "zoxide"
brew "goenv"
brew "pyenv"

# brew --caskいる系？
brew "hiddenbar"
brew "raycast"

# # windowマネジャー
# brew "yabai"
# brew "skhd"
brew "terragrunt"

# protocol buffers
brew "bufbuild/buf/buf"
brew tap "yoheimuta/protolint"
