tap 'homebrew/cask'
tap 'homebrew/core'
tap "homebrew/cask-fonts"
tap "ktr0731/evans"

# Neovim
brew "ripgrep"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

brew "bat"
brew "exa"

brew "go-to-k/tap/cls3"
brew "fujiwara/tap/tracer"
brew "zoxide"

# brew --caskいる系？
brew "hiddenbar"
brew "raycast"

# # windowマネジャー
# brew "yabai"
# brew "skhd"
brew "terragrunt"
